{% set name = "nest-desktop" %}
{% set version = "4.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/nest_desktop-{{ version }}.tar.gz
  sha256: 037d637a240f42bc6d8b3d44e46b6fdc7dcd1cbe76b2c9f2bbfcd813e51f3e2d

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}

test:
  imports:
    - nest_desktop
  commands:
    - pip check
    - nest-desktop status  # [unix]
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://nest-desktop.github.io
  license: MIT
  license_file: LICENSE
  summary: NEST Desktop is a web-based application for NEST Simulator.
  description: |
    NEST Desktop is a web-based application which provides a graphical user interface for NEST Simulator. With this
    easy-to-use tool, users can interactively construct neuronal networks and explore network dynamics. Advanced users
    often choose NEST Simulator: a prominent tool for spiking neuronal networks to measure network dynamics. However,
    programming knowledge is required to write code for this tool. NEST Desktop bypasses this requirement, but still
    teaches users how to construct and explore neuronal networks. A textual script is generated from the constructed
    networks and sent to NEST Simulator; the network activity is then visualized in a graph or table. It is a useful
    teaching tool, since the network graphs and network activity visualizations can be exported to files that users can
    implement for their course protocol.
  dev_url: https://github.com/nest-desktop/nest-desktop
  doc_url: https://nest-desktop.readthedocs.io
  doc_source_url: https://github.com/nest-desktop/nest-desktop/blob/master/README.rst

extra:
  recipe-maintainers:
    - babsey
